version: '3.8'

services:
  rabbitmq:
    container_name: plan_rabbitmq
    # image: rabbitmq:3-management

    environment:
      RABBITMQ_DEFAULT_USER: yu
      RABBITMQ_DEFAULT_PASS: yu
      RABBITMQ_DEFAULT_VHOST: /
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    volumes:
      - ..:/workspace/plan:cached

  vosk:
    image: alpine:latest
 